
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.60.0.  DO NOT EDIT!
//*************************************************************************************

using System.Text.RegularExpressions;

namespace XTC.FMP.MOD.VisionLayout.LIB.Unity
{
    /// <summary>
    /// 资源包的meta结构
    /// </summary>
    public class BundleMetaSchema
    {
        /// <summary>
        /// 路径是否匹配表达式
        /// </summary>
        /// <param name="_contentUri">内容的短路径</param>
        /// <param name="_pattern">正则表达式</param>
        /// <returns>是否匹配</returns>
        public static bool IsMatch(string _contentUri, string _pattern)
        {
            Regex regex = new Regex(_pattern);
            return regex.IsMatch(_contentUri);
        }

        /// <summary>
        /// 内容名称的列表
        /// </summary>
        public string[] contentS { get; set; } = new string[0];
    } //class

    /// <summary>
    /// 资源内容的meta结构
    /// </summary>
    public class ContentMetaSchema
    {
    } //class
} //namespace

