
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.61.0.  DO NOT EDIT!
//*************************************************************************************
public abstract class IntegrationTestBase
{
    [Fact]
    public abstract Task Test();
}
